Repository apmath-web/loans, pull requests merged in 2019-05, with the labels that each got.

#27 Fix docker
  .travis.yml
  README.md
  build.gradle
  resources/application.conf
  src/com/apmath/loans/infrastructure/fetchers/Host.kt
Labels: Ready

#32 Fix env with hosts
  src/com/apmath/loans/infrastructure/fetchers/Host.kt
Labels: bug

#28 Action API: List of loans
  src/com/apmath/loans/application/v1/Api.kt
  src/com/apmath/loans/application/v1/actions/Abstract.kt
  src/com/apmath/loans/application/v1/actions/Create.kt
  src/com/apmath/loans/application/v1/actions/Info.kt
  src/com/apmath/loans/application/v1/actions/ListLoans.kt
  src/com/apmath/loans/application/v1/mappers/LoanMapper.kt
  src/com/apmath/loans/application/v1/mappers/LoansMapper.kt
  src/com/apmath/loans/application/v1/models/Info.kt
  src/com/apmath/loans/application/v1/models/incoming/Info.kt
  src/com/apmath/loans/application/v1/models/incoming/Loan.kt
  src/com/apmath/loans/application/v1/models/incoming/LoansListRequest.kt
  src/com/apmath/loans/application/v1/models/incoming/Payment.kt
  src/com/apmath/loans/application/v1/models/outgoing/ResponseLoan.kt
  src/com/apmath/loans/application/v1/models/response/LoanIdResponse.kt
  src/com/apmath/loans/domain/exceptions/runtime/ChangeIdentifiedCreditIdException.kt
  src/com/apmath/loans/domain/models/loans/Loan.kt
  src/com/apmath/loans/domain/services/LoanService.kt
  src/com/apmath/loans/domain/services/LoanServiceInterface.kt
Labels: Ready, api

#29 Action BL: List of loans
  src/com/apmath/loans/Application.kt
  src/com/apmath/loans/application/v1/Api.kt
  src/com/apmath/loans/application/v1/actions/Create.kt
  src/com/apmath/loans/application/v1/actions/ListLoans.kt
  src/com/apmath/loans/application/v1/exceptions/ApiException.kt
  src/com/apmath/loans/application/v1/exceptions/BadRequestException.kt
  src/com/apmath/loans/application/v1/exceptions/BadRequestValidationException.kt
  src/com/apmath/loans/application/v1/exceptions/ForbiddenException.kt
  src/com/apmath/loans/application/v1/exceptions/NotFoundException.kt
  src/com/apmath/loans/application/v1/mappers/LoansMapper.kt
  src/com/apmath/loans/domain/exceptions/ApiException.kt
  src/com/apmath/loans/domain/exceptions/ForbiddenAccessException.kt
  src/com/apmath/loans/domain/exceptions/NoClientException.kt
  src/com/apmath/loans/domain/exceptions/NotApprovedException.kt
  src/com/apmath/loans/domain/exceptions/WrongAmountException.kt
  src/com/apmath/loans/domain/exceptions/WrongClientId.kt
  src/com/apmath/loans/domain/models/MixedId.kt
  src/com/apmath/loans/domain/models/MixedIdInterface.kt
  src/com/apmath/loans/domain/repositories/Repository.kt
  src/com/apmath/loans/domain/repositories/RepositoryInterface.kt
  src/com/apmath/loans/domain/services/LoanService.kt
  src/com/apmath/loans/domain/services/LoanServiceInterface.kt
Labels: Ready, business logic

#45 Fix loan's create route
  src/com/apmath/loans/application/v1/Api.kt
Labels: Ready, api, bug

#30 Action API: Loan's payments
  src/com/apmath/loans/application/v1/Api.kt
  src/com/apmath/loans/application/v1/actions/Abstract.kt
  src/com/apmath/loans/application/v1/actions/PaymentList.kt
  src/com/apmath/loans/domain/services/PaymentService.kt
  src/com/apmath/loans/domain/services/PaymentServiceInterface.kt
  src/com/apmath/loans/infrastructure/Module.kt
Labels: Ready, api

#33 Action API: Payment
  src/com/apmath/loans/application/v1/Api.kt
  src/com/apmath/loans/application/v1/actions/Abstract.kt
  src/com/apmath/loans/application/v1/actions/ListLoans.kt
  src/com/apmath/loans/application/v1/actions/Payment.kt
  src/com/apmath/loans/application/v1/models/incoming/Payment.kt
  src/com/apmath/loans/application/v1/validators/PaymentBuilder.kt
  src/com/apmath/loans/domain/models/MixedId.kt
  src/com/apmath/loans/domain/models/MixedIdInterface.kt
  src/com/apmath/loans/domain/models/payments/Payment.kt
  src/com/apmath/loans/domain/models/payments/PaymentInterface.kt
  src/com/apmath/loans/domain/services/LoanService.kt
  src/com/apmath/loans/domain/services/PaymentService.kt
  src/com/apmath/loans/domain/services/PaymentServiceInterface.kt
Labels: Ready, api

#47 Input parameters for loan's payments method fix
  src/com/apmath/loans/application/v1/actions/PaymentList.kt
  src/com/apmath/loans/domain/services/PaymentService.kt
  src/com/apmath/loans/domain/services/PaymentServiceInterface.kt
Labels: bug

#44 Fix ApplicationFetcher with new specification
  src/com/apmath/loans/application/v1/actions/Create.kt
  src/com/apmath/loans/domain/fetchers/ApplicationsFetcherInterface.kt
  src/com/apmath/loans/domain/models/ApplicationDetailsInterface.kt
  src/com/apmath/loans/domain/models/ApplicationInterface.kt
  src/com/apmath/loans/domain/models/loans/LoanCreationData.kt
  src/com/apmath/loans/domain/services/LoanService.kt
  src/com/apmath/loans/infrastructure/fetchers/ApplicationsFetcher.kt
  src/com/apmath/loans/infrastructure/fetchers/CalculationsFetcher.kt
  src/com/apmath/loans/infrastructure/fetchers/ClientsFetcher.kt
  src/com/apmath/loans/infrastructure/models/Application.kt
  src/com/apmath/loans/infrastructure/models/ApplicationDetails.kt
Labels: bug, business logic

#49 Some major fixes
  resources/application.conf
  src/com/apmath/loans/Application.kt
  src/com/apmath/loans/application/v1/actions/Abstract.kt
  src/com/apmath/loans/infrastructure/fetchers/Host.kt
Labels: Ready, bug

#42 register Type Adapter for LocalDate
  src/com/apmath/loans/Application.kt
Labels: Ready
